# Site settings
title:
email: pinkisharma03@yahoo.com
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser
