# Site settings
title: Before and After School Daycare
email: pinkisharma03@yahoo.com
author:
description: Before After School Day care in Fremont Niles area, close to Bart
url: www.brilliantchildren.net
logo: /img/logo.jpg

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: someGithubUser
twitter_username: someTwitterUser
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      canonical_url: 'http://www.brilliantchildren.net'